language: java
jdk: openjdk10
cache:
  directories:
    - "$HOME/.m2"
before_install:
  - curl -O https://raw.githubusercontent.com/linksmart/ci-scripts/master/java/ci-preparation.sh
  - chmod +x ci-preparation.sh
  - . ./ci-preparation.sh
  - echo $TRAVIS_REPO_SLUG
deploy:
  - provider: script
    script: ./maven-release.sh
    skip_cleanup: true
    on:
      branch: release
  - provider: script
    script: mvn deploy
    skip_cleanup: true
    on:
      branch: master
