language: java
jdk: openjdk10
cache:
  directories:
    - "$HOME/.m2"
before_install:
  - if [ "$TRAVIS_BRANCH" = "release" ]; then export ARTIFACT_VERSION=`python3 .versionScript.py`; fi
  - echo $TRAVIS_BRANCH
  - echo $ARTIFACT_VERSION
  - python3 --version
deploy:
  - provider: script
    script: mvn deploy
    skip_cleanup: true
    on:
      branch: release
  - provider: script
    script: mvn deploy
    skip_cleanup: true
    on:
      branch: master
after_deploy:
  - "if [ '$TRAVIS_BRANCH' = 'release' ]; then git commit -am '[skip travis] AUTOMATIC COMMIT: tagging version'; fi"
  - "if [ '$TRAVIS_BRANCH' = 'release' ]; then git config --global user.email 'travis@travis-ci.org'; fi"
  - "if [ '$TRAVIS_BRANCH' = 'release' ]; then git config --global user.name 'Travis CI'; fi"
  - "if [ '$TRAVIS_BRANCH' = 'release' ]; then git branch tmp; fi"
  - "if [ '$TRAVIS_BRANCH' = 'release' ]; then git checkout release; fi"
  - "if [ '$TRAVIS_BRANCH' = 'release' ]; then git merge tmp; fi"
  - "if [ '$TRAVIS_BRANCH' = 'release' ]; then git branch -d tmp; fi"
  - "if [ '$TRAVIS_BRANCH' = 'release' ]; then git checkout master; fi"
  - "if [ '$TRAVIS_BRANCH' = 'release' ]; then git merge release; fi"
  - "if [ '$TRAVIS_BRANCH' = 'release' ]; then python3 .versionScript.py; fi"
  - "if [ '$TRAVIS_BRANCH' = 'release' ]; then git push https://${GH_TOKEN}@github.com/linksmart/linksmart-java-utils.git --all --tags; fi"