language: java
jdk: openjdk10
cache:
  directories:
    - "$HOME/.m2"
before_install: if [ "$TRAVIS_BRANCH" = "master" ]; then export ARTIFACT_VERSION=`python  .versionScript.py --versionType release`; fi
deploy:
  - provider: script
    script: mvn deploy
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: mvn deploy
    skip_cleanup: true
    on:
      branch: master
after_deploy:
  - "if [ '$TRAVIS_BRANCH' = 'master' ]; then python .versionScript.py --versionType minor; fi"
  - "if [ '$TRAVIS_BRANCH' = 'master' ] git commit -am '[skip travis] AUTOMATIC COMMIT: tagging version'"
  - "if [ '$TRAVIS_BRANCH' = 'master' ] git config --global user.email 'travis@travis-ci.org'"
  - "if [ '$TRAVIS_BRANCH' = 'master' ] git config --global user.name 'Travis CI'"
  - "if [ '$TRAVIS_BRANCH' = 'master' ] git branch tmp"
  - "if [ '$TRAVIS_BRANCH' = 'master' ] git checkout dev"
  - "if [ '$TRAVIS_BRANCH' = 'master' ] git merge tmp"
  - "if [ '$TRAVIS_BRANCH' = 'master' ] git branch -d tmp"
  - "if [ '$TRAVIS_BRANCH' = 'master' ] git push https://${GH_TOKEN}@github.com/linksmart/linksmart-java-utils.git --all --tags"