language: java
jdk: openjdk10
cache:
  directories:
    - "$HOME/.m2"
before_install: curl -s https://raw.githubusercontent.com/linksmart/ci-scripts/master/java/ci-preparation.sh | bash
deploy:
  - provider: script
    script: curl -s https://raw.githubusercontent.com/linksmart/ci-scripts/master/java/maven-release.sh | bash
    skip_cleanup: true
    on:
      branch: release
  - provider: script
    script: mvn deploy
    skip_cleanup: true
    on:
      branch: master
